config/routes.rb
Rails.application.routes.draw do
  get 'analysis/new'

  get 'sessions/new'

  get 'users/new'

  root 'main_pages#home'

  get 'main_pages/aboutus'
  
  get 'main_pages/home'
  
  get 'laststate' => 'analyses#laststate'
  
  get 'mainpanel' => 'mainpanel#index'

  get 'newanalysis' => 'analyses#new'
  
  get 'signup'  => 'users#new'
  
  get '/main_pages/contactus'
  
  get 'recommendation' => 'recommendation#index'
  get 'rec_nutrition' => 'recommendation#nutrition'
  get 'rec_exercise' => 'recommendation#exercise'
  get 'rec_dailyTips' => 'recommendation#dailyTips'
  get 'rec_mobileapp' => 'recommendation#mobileapp'
  resources :users
  
  resources :analyses
  resources :analysis_steps
  
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
end

app/controllers/analyses_controller.rb
class AnalysesController < ApplicationController
  before_action :set_analysis, only: [:show, :edit, :update, :destroy]

  # GET /analyses
  # GET /analyses.json
  def index
    @analyses = Analysis.all
  end

  # GET /analyses/1
  # GET /analyses/1.json
  def show
   
  end
  
  def laststate
   @analysis = Analysis.find(1)
  end

  # GET /analyses/new
  def new
    
    @analysis = Analysis.new
    
  end

  def edit
  end
def create
  oldexist = Analysis.find_by(userid: current_user.id)
  if oldexist == nil
    @analysis = Analysis.new(analysis_params)
    @analysis.userid = current_user.id
    @analysis.avalue = calculate_a_value
    if @analysis.save
      session[:analysis_id] = @analysis.id
      redirect_to analysis_steps_path
    else
      render :new
    end
  else
    @analysis = oldexist
    @analysis.update_attributes(analysis_params)
    @analysis.userid = current_user.id
    @analysis.avalue = calculate_a_value
    @analysis.save
    session[:analysis_id] = @analysis.id
    redirect_to analysis_steps_path
  end
end
  # PATCH/PUT /analyses/1
  # PATCH/PUT /analyses/1.json
  def update
    respond_to do |format|
      if @analysis.update(analysis_params)
        format.html { redirect_to @analysis, notice: 'Analysis was successfully updated.' }
        format.json { render :show, status: :ok, location: @analysis }
      else
        format.html { render :edit }
        format.json { render json: @analysis.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /analyses/1
  # DELETE /analyses/1.json
  def destroy
    @analysis.destroy
    respond_to do |format|
      format.html { redirect_to analyses_url, notice: 'Analysis was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_analysis
      @analysis = Analysis.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def analysis_params
      params.require(:analysis).permit(:userid, :weight, :length, :waist, :hip, :avalue, :push_up, :sit_up, :bvalue, :phalanx_number, :cvalue, :fitness)
    end
    
    def calculate_a_value
      alfa = @analysis.waist.fdiv(@analysis.hip)
      beta = @analysis.weight.fdiv(@analysis.length * @analysis.length )
      if current_user.sex == "female" and alfa > 0.95
        return 1
      end
      if current_user.sex == "male" and alfa > 0.8
        return 1
      end
      if beta >= 40
        return 2
      elsif beta >=30 and beta <40
        return 3
      elsif beta >=25 and beta <30
        return 4
      elsif beta >=18.5 and beta <25
        return 5
      end
      return -1
    end
end

app/helpers/analyses_helper.rb
module AnalysesHelper
end

app/views/analyses/_form.html.erb
<%= form_for(@analysis) do |f| %>
  <% if @analysis.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@analysis.errors.count, "error") %> prohibited this analysis from being saved:</h2>

      <ul>
      <% @analysis.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :userid %><br>
    <%= f.number_field :userid %>
  </div>
  <div class="field">
    <%= f.label :weight %><br>
    <%= f.number_field :weight %>
  </div>
  <div class="field">
    <%= f.label :length %><br>
    <%= f.number_field :length %>
  </div>
  <div class="field">
    <%= f.label :waist %><br>
    <%= f.number_field :waist %>
  </div>
  <div class="field">
    <%= f.label :hip %><br>
    <%= f.number_field :hip %>
  </div>
  <div class="field">
    <%= f.label :avalue %><br>
    <%= f.number_field :avalue %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/analyses/edit.html.erb
<h1>Editing Analysis</h1>

<%= render 'form' %>

<%= link_to 'Show', @analysis %> |
<%= link_to 'Back', analyses_path %>

app/views/analyses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Analyses</h1>

<table>
  <thead>
    <tr>
      <th>Userid</th>
      <th>Weight</th>
      <th>Length</th>
      <th>Waist</th>
      <th>Hip</th>
      <th>Avalue</th>
      <th>Push up</th>
      <th>Sit up</th>
      <th>Bvalue</th>
      <th>Phalanx number</th>
      <th>Cvalue</th>
      <th>Fitness</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @analyses.each do |analysis| %>
      <tr>
        <td><%= analysis.userid %></td>
        <td><%= analysis.weight %></td>
        <td><%= analysis.length %></td>
        <td><%= analysis.waist %></td>
        <td><%= analysis.hip %></td>
        <td><%= analysis.avalue %></td>
        <td><%= analysis.push_up %></td>
        <td><%= analysis.sit_up %></td>
        <td><%= analysis.bvalue %></td>
        <td><%= analysis.phalanx_number %></td>
        <td><%= analysis.cvalue %></td>
        <td><%= analysis.fitness %></td>
        <td><%= link_to 'Show', analysis %></td>
        <td><%= link_to 'Edit', edit_analysis_path(analysis) %></td>
        <td><%= link_to 'Destroy', analysis, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Analysis', new_analysis_path %>

app/views/analyses/laststate.html.erb
<br/>
<br/>
<p>
  <strong>Your Fitness:</strong>
  <%= @analysis.fitness %>
</p>

<p>
  <strong>Body Fat Distribution:</strong>
  <%= @analysis.avalue %>
</p>
<p>
  <strong>Muscular Endurance:</strong>
  <%= @analysis.bvalue %>
</p>
<p>
  <strong>Stretchiness of Body:</strong>
  <%= @analysis.cvalue %>
</p>

app/views/analyses/new.html.erb
<h1>New Analysis</h1>
<%= form_for(@analysis) do |f| %>
  <% if @analysis.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@analysis.errors.count, "error") %> prohibited this analysis from being saved:</h2>

      <ul>
      <% @analysis.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :weight %><br>
    <%= f.text_field :weight %>
  </div>
  <div class="field">
    <%= f.label :length %><br>
    <%= f.text_field :length %>
  </div>
  <div class="field">
    <%= f.label :waist %><br>
    <%= f.text_field :waist %>
  </div>
  <div class="field">
    <%= f.label :hip %><br>
    <%= f.text_field :hip %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', analyses_path %>

app/views/analyses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Userid:</strong>
  <%= @analysis.userid %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @analysis.weight %>
</p>

<p>
  <strong>Length:</strong>
  <%= @analysis.length %>
</p>

<p>
  <strong>Waist:</strong>
  <%= @analysis.waist %>
</p>

<p>
  <strong>Hip:</strong>
  <%= @analysis.hip %>
</p>

<p>
  <strong>Avalue:</strong>
  <%= @analysis.avalue %>
</p>

<p>
  <strong>Push up:</strong>
  <%= @analysis.push_up %>
</p>

<p>
  <strong>Sit up:</strong>
  <%= @analysis.sit_up %>
</p>

<p>
  <strong>Bvalue:</strong>
  <%= @analysis.bvalue %>
</p>

<p>
  <strong>Phalanx number:</strong>
  <%= @analysis.phalanx_number %>
</p>

<p>
  <strong>Cvalue:</strong>
  <%= @analysis.cvalue %>
</p>

<p>
  <strong>Fitness:</strong>
  <%= @analysis.fitness %>
</p>

<%= link_to 'Edit', edit_analysis_path(@analysis) %> |
<%= link_to 'Back', analyses_path %>