config/routes.rb
Rails.application.routes.draw do
  get 'analysis/new'

  get 'sessions/new'

  get 'users/new'

  root 'main_pages#home'

  get 'main_pages/aboutus'
  
  get 'main_pages/home'
  
  get 'laststate' => 'analyses#laststate'
  
  get 'mainpanel' => 'mainpanel#index'

  get 'newanalysis' => 'analyses#new'
  
  get 'signup'  => 'users#new'
  
  get '/main_pages/contactus'
  
  get 'recommendation' => 'recommendation#index'
  get 'rec_nutrition' => 'recommendation#nutrition'
  get 'rec_exercise' => 'recommendation#exercise'
  get 'rec_dailyTips' => 'recommendation#dailyTips'
  get 'rec_mobileapp' => 'recommendation#mobileapp'
  resources :users
  
  resources :analyses
  resources :analysis_steps
  
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Health Fitness Assistant</title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
  <body>
    <header class="navbar  navbar-red">
      <div class="container">
          <h1 class="whitecolor">Health $ Fitness Assistant</h1>
          <h5 class="title"> Nothing is not important than health</h6>
        <nav>
          <ul class="nav navbar-nav">
            <li><%= link_to "Home",   '/' %></li>
            <li><%= link_to "About Us",   '/main_pages/aboutus' %></li>
            <li><%= link_to "Contact Us", '/main_pages/contactus' %></li>
            <% if logged_in? %>
            <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= current_user.username %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Main Panel", '/mainpanel' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
          <% else %>
            <li><%= link_to "Log in", login_path %></li>
          <% end %>
          </ul>
        </nav>
      </div>
    </header>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %> topmargin"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>